# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = N:\RayTracing\FS26

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "N:\RayTracing\FS26\Neu2026 (minimalistisch)"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "N:\RayTracing\FS26\Neu2026 (minimalistisch)\CMakeFiles" "N:\RayTracing\FS26\Neu2026 (minimalistisch)\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "N:\RayTracing\FS26\Neu2026 (minimalistisch)\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named programm

# Build rule for target.
programm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 programm
.PHONY : programm

# fast build rule for target.
programm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/build
.PHONY : programm/fast

camera.obj: camera.cpp.obj
.PHONY : camera.obj

# target to build an object file
camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/camera.cpp.obj
.PHONY : camera.cpp.obj

camera.i: camera.cpp.i
.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s
.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/camera.cpp.s
.PHONY : camera.cpp.s

cube.obj: cube.cpp.obj
.PHONY : cube.obj

# target to build an object file
cube.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/cube.cpp.obj
.PHONY : cube.cpp.obj

cube.i: cube.cpp.i
.PHONY : cube.i

# target to preprocess a source file
cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/cube.cpp.i
.PHONY : cube.cpp.i

cube.s: cube.cpp.s
.PHONY : cube.s

# target to generate assembly for a file
cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/cube.cpp.s
.PHONY : cube.cpp.s

dreieck.obj: dreieck.cpp.obj
.PHONY : dreieck.obj

# target to build an object file
dreieck.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/dreieck.cpp.obj
.PHONY : dreieck.cpp.obj

dreieck.i: dreieck.cpp.i
.PHONY : dreieck.i

# target to preprocess a source file
dreieck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/dreieck.cpp.i
.PHONY : dreieck.cpp.i

dreieck.s: dreieck.cpp.s
.PHONY : dreieck.s

# target to generate assembly for a file
dreieck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/dreieck.cpp.s
.PHONY : dreieck.cpp.s

farbe.obj: farbe.cpp.obj
.PHONY : farbe.obj

# target to build an object file
farbe.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/farbe.cpp.obj
.PHONY : farbe.cpp.obj

farbe.i: farbe.cpp.i
.PHONY : farbe.i

# target to preprocess a source file
farbe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/farbe.cpp.i
.PHONY : farbe.cpp.i

farbe.s: farbe.cpp.s
.PHONY : farbe.s

# target to generate assembly for a file
farbe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/farbe.cpp.s
.PHONY : farbe.cpp.s

fenster.obj: fenster.cpp.obj
.PHONY : fenster.obj

# target to build an object file
fenster.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/fenster.cpp.obj
.PHONY : fenster.cpp.obj

fenster.i: fenster.cpp.i
.PHONY : fenster.i

# target to preprocess a source file
fenster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/fenster.cpp.i
.PHONY : fenster.cpp.i

fenster.s: fenster.cpp.s
.PHONY : fenster.s

# target to generate assembly for a file
fenster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/fenster.cpp.s
.PHONY : fenster.cpp.s

kugel.obj: kugel.cpp.obj
.PHONY : kugel.obj

# target to build an object file
kugel.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/kugel.cpp.obj
.PHONY : kugel.cpp.obj

kugel.i: kugel.cpp.i
.PHONY : kugel.i

# target to preprocess a source file
kugel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/kugel.cpp.i
.PHONY : kugel.cpp.i

kugel.s: kugel.cpp.s
.PHONY : kugel.s

# target to generate assembly for a file
kugel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/kugel.cpp.s
.PHONY : kugel.cpp.s

light.obj: light.cpp.obj
.PHONY : light.obj

# target to build an object file
light.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/light.cpp.obj
.PHONY : light.cpp.obj

light.i: light.cpp.i
.PHONY : light.i

# target to preprocess a source file
light.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/light.cpp.i
.PHONY : light.cpp.i

light.s: light.cpp.s
.PHONY : light.s

# target to generate assembly for a file
light.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/light.cpp.s
.PHONY : light.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/main.cpp.s
.PHONY : main.cpp.s

material.obj: material.cpp.obj
.PHONY : material.obj

# target to build an object file
material.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/material.cpp.obj
.PHONY : material.cpp.obj

material.i: material.cpp.i
.PHONY : material.i

# target to preprocess a source file
material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/material.cpp.i
.PHONY : material.cpp.i

material.s: material.cpp.s
.PHONY : material.s

# target to generate assembly for a file
material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/material.cpp.s
.PHONY : material.cpp.s

material_library.obj: material_library.cpp.obj
.PHONY : material_library.obj

# target to build an object file
material_library.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/material_library.cpp.obj
.PHONY : material_library.cpp.obj

material_library.i: material_library.cpp.i
.PHONY : material_library.i

# target to preprocess a source file
material_library.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/material_library.cpp.i
.PHONY : material_library.cpp.i

material_library.s: material_library.cpp.s
.PHONY : material_library.s

# target to generate assembly for a file
material_library.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/material_library.cpp.s
.PHONY : material_library.cpp.s

mauspicking.obj: mauspicking.cpp.obj
.PHONY : mauspicking.obj

# target to build an object file
mauspicking.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/mauspicking.cpp.obj
.PHONY : mauspicking.cpp.obj

mauspicking.i: mauspicking.cpp.i
.PHONY : mauspicking.i

# target to preprocess a source file
mauspicking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/mauspicking.cpp.i
.PHONY : mauspicking.cpp.i

mauspicking.s: mauspicking.cpp.s
.PHONY : mauspicking.s

# target to generate assembly for a file
mauspicking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/mauspicking.cpp.s
.PHONY : mauspicking.cpp.s

mausray.obj: mausray.cpp.obj
.PHONY : mausray.obj

# target to build an object file
mausray.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/mausray.cpp.obj
.PHONY : mausray.cpp.obj

mausray.i: mausray.cpp.i
.PHONY : mausray.i

# target to preprocess a source file
mausray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/mausray.cpp.i
.PHONY : mausray.cpp.i

mausray.s: mausray.cpp.s
.PHONY : mausray.s

# target to generate assembly for a file
mausray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/mausray.cpp.s
.PHONY : mausray.cpp.s

mesh.obj: mesh.cpp.obj
.PHONY : mesh.obj

# target to build an object file
mesh.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/mesh.cpp.obj
.PHONY : mesh.cpp.obj

mesh.i: mesh.cpp.i
.PHONY : mesh.i

# target to preprocess a source file
mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/mesh.cpp.i
.PHONY : mesh.cpp.i

mesh.s: mesh.cpp.s
.PHONY : mesh.s

# target to generate assembly for a file
mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/mesh.cpp.s
.PHONY : mesh.cpp.s

mesh_importer.obj: mesh_importer.cpp.obj
.PHONY : mesh_importer.obj

# target to build an object file
mesh_importer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/mesh_importer.cpp.obj
.PHONY : mesh_importer.cpp.obj

mesh_importer.i: mesh_importer.cpp.i
.PHONY : mesh_importer.i

# target to preprocess a source file
mesh_importer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/mesh_importer.cpp.i
.PHONY : mesh_importer.cpp.i

mesh_importer.s: mesh_importer.cpp.s
.PHONY : mesh_importer.s

# target to generate assembly for a file
mesh_importer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/mesh_importer.cpp.s
.PHONY : mesh_importer.cpp.s

obj_import_dialog.obj: obj_import_dialog.cpp.obj
.PHONY : obj_import_dialog.obj

# target to build an object file
obj_import_dialog.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/obj_import_dialog.cpp.obj
.PHONY : obj_import_dialog.cpp.obj

obj_import_dialog.i: obj_import_dialog.cpp.i
.PHONY : obj_import_dialog.i

# target to preprocess a source file
obj_import_dialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/obj_import_dialog.cpp.i
.PHONY : obj_import_dialog.cpp.i

obj_import_dialog.s: obj_import_dialog.cpp.s
.PHONY : obj_import_dialog.s

# target to generate assembly for a file
obj_import_dialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/obj_import_dialog.cpp.s
.PHONY : obj_import_dialog.cpp.s

pfeil.obj: pfeil.cpp.obj
.PHONY : pfeil.obj

# target to build an object file
pfeil.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/pfeil.cpp.obj
.PHONY : pfeil.cpp.obj

pfeil.i: pfeil.cpp.i
.PHONY : pfeil.i

# target to preprocess a source file
pfeil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/pfeil.cpp.i
.PHONY : pfeil.cpp.i

pfeil.s: pfeil.cpp.s
.PHONY : pfeil.s

# target to generate assembly for a file
pfeil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/pfeil.cpp.s
.PHONY : pfeil.cpp.s

preprocessing.obj: preprocessing.cpp.obj
.PHONY : preprocessing.obj

# target to build an object file
preprocessing.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/preprocessing.cpp.obj
.PHONY : preprocessing.cpp.obj

preprocessing.i: preprocessing.cpp.i
.PHONY : preprocessing.i

# target to preprocess a source file
preprocessing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/preprocessing.cpp.i
.PHONY : preprocessing.cpp.i

preprocessing.s: preprocessing.cpp.s
.PHONY : preprocessing.s

# target to generate assembly for a file
preprocessing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/preprocessing.cpp.s
.PHONY : preprocessing.cpp.s

raster_placement.obj: raster_placement.cpp.obj
.PHONY : raster_placement.obj

# target to build an object file
raster_placement.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/raster_placement.cpp.obj
.PHONY : raster_placement.cpp.obj

raster_placement.i: raster_placement.cpp.i
.PHONY : raster_placement.i

# target to preprocess a source file
raster_placement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/raster_placement.cpp.i
.PHONY : raster_placement.cpp.i

raster_placement.s: raster_placement.cpp.s
.PHONY : raster_placement.s

# target to generate assembly for a file
raster_placement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/raster_placement.cpp.s
.PHONY : raster_placement.cpp.s

ray.obj: ray.cpp.obj
.PHONY : ray.obj

# target to build an object file
ray.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/ray.cpp.obj
.PHONY : ray.cpp.obj

ray.i: ray.cpp.i
.PHONY : ray.i

# target to preprocess a source file
ray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/ray.cpp.i
.PHONY : ray.cpp.i

ray.s: ray.cpp.s
.PHONY : ray.s

# target to generate assembly for a file
ray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/ray.cpp.s
.PHONY : ray.cpp.s

render.obj: render.cpp.obj
.PHONY : render.obj

# target to build an object file
render.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/render.cpp.obj
.PHONY : render.cpp.obj

render.i: render.cpp.i
.PHONY : render.i

# target to preprocess a source file
render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/render.cpp.i
.PHONY : render.cpp.i

render.s: render.cpp.s
.PHONY : render.s

# target to generate assembly for a file
render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/render.cpp.s
.PHONY : render.cpp.s

rotations.obj: rotations.cpp.obj
.PHONY : rotations.obj

# target to build an object file
rotations.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/rotations.cpp.obj
.PHONY : rotations.cpp.obj

rotations.i: rotations.cpp.i
.PHONY : rotations.i

# target to preprocess a source file
rotations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/rotations.cpp.i
.PHONY : rotations.cpp.i

rotations.s: rotations.cpp.s
.PHONY : rotations.s

# target to generate assembly for a file
rotations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/rotations.cpp.s
.PHONY : rotations.cpp.s

scene.obj: scene.cpp.obj
.PHONY : scene.obj

# target to build an object file
scene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/scene.cpp.obj
.PHONY : scene.cpp.obj

scene.i: scene.cpp.i
.PHONY : scene.i

# target to preprocess a source file
scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/scene.cpp.i
.PHONY : scene.cpp.i

scene.s: scene.cpp.s
.PHONY : scene.s

# target to generate assembly for a file
scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/scene.cpp.s
.PHONY : scene.cpp.s

stab.obj: stab.cpp.obj
.PHONY : stab.obj

# target to build an object file
stab.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/stab.cpp.obj
.PHONY : stab.cpp.obj

stab.i: stab.cpp.i
.PHONY : stab.i

# target to preprocess a source file
stab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/stab.cpp.i
.PHONY : stab.cpp.i

stab.s: stab.cpp.s
.PHONY : stab.s

# target to generate assembly for a file
stab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/stab.cpp.s
.PHONY : stab.cpp.s

text3d.obj: text3d.cpp.obj
.PHONY : text3d.obj

# target to build an object file
text3d.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/text3d.cpp.obj
.PHONY : text3d.cpp.obj

text3d.i: text3d.cpp.i
.PHONY : text3d.i

# target to preprocess a source file
text3d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/text3d.cpp.i
.PHONY : text3d.cpp.i

text3d.s: text3d.cpp.s
.PHONY : text3d.s

# target to generate assembly for a file
text3d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/text3d.cpp.s
.PHONY : text3d.cpp.s

threading.obj: threading.cpp.obj
.PHONY : threading.obj

# target to build an object file
threading.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/threading.cpp.obj
.PHONY : threading.cpp.obj

threading.i: threading.cpp.i
.PHONY : threading.i

# target to preprocess a source file
threading.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/threading.cpp.i
.PHONY : threading.cpp.i

threading.s: threading.cpp.s
.PHONY : threading.s

# target to generate assembly for a file
threading.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/threading.cpp.s
.PHONY : threading.cpp.s

vector3d.obj: vector3d.cpp.obj
.PHONY : vector3d.obj

# target to build an object file
vector3d.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/vector3d.cpp.obj
.PHONY : vector3d.cpp.obj

vector3d.i: vector3d.cpp.i
.PHONY : vector3d.i

# target to preprocess a source file
vector3d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/vector3d.cpp.i
.PHONY : vector3d.cpp.i

vector3d.s: vector3d.cpp.s
.PHONY : vector3d.s

# target to generate assembly for a file
vector3d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/vector3d.cpp.s
.PHONY : vector3d.cpp.s

wand.obj: wand.cpp.obj
.PHONY : wand.obj

# target to build an object file
wand.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wand.cpp.obj
.PHONY : wand.cpp.obj

wand.i: wand.cpp.i
.PHONY : wand.i

# target to preprocess a source file
wand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wand.cpp.i
.PHONY : wand.cpp.i

wand.s: wand.cpp.s
.PHONY : wand.s

# target to generate assembly for a file
wand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wand.cpp.s
.PHONY : wand.cpp.s

wireframe.obj: wireframe.cpp.obj
.PHONY : wireframe.obj

# target to build an object file
wireframe.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe.cpp.obj
.PHONY : wireframe.cpp.obj

wireframe.i: wireframe.cpp.i
.PHONY : wireframe.i

# target to preprocess a source file
wireframe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe.cpp.i
.PHONY : wireframe.cpp.i

wireframe.s: wireframe.cpp.s
.PHONY : wireframe.s

# target to generate assembly for a file
wireframe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe.cpp.s
.PHONY : wireframe.cpp.s

wireframe_front.obj: wireframe_front.cpp.obj
.PHONY : wireframe_front.obj

# target to build an object file
wireframe_front.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe_front.cpp.obj
.PHONY : wireframe_front.cpp.obj

wireframe_front.i: wireframe_front.cpp.i
.PHONY : wireframe_front.i

# target to preprocess a source file
wireframe_front.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe_front.cpp.i
.PHONY : wireframe_front.cpp.i

wireframe_front.s: wireframe_front.cpp.s
.PHONY : wireframe_front.s

# target to generate assembly for a file
wireframe_front.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe_front.cpp.s
.PHONY : wireframe_front.cpp.s

wireframe_perspective.obj: wireframe_perspective.cpp.obj
.PHONY : wireframe_perspective.obj

# target to build an object file
wireframe_perspective.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe_perspective.cpp.obj
.PHONY : wireframe_perspective.cpp.obj

wireframe_perspective.i: wireframe_perspective.cpp.i
.PHONY : wireframe_perspective.i

# target to preprocess a source file
wireframe_perspective.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe_perspective.cpp.i
.PHONY : wireframe_perspective.cpp.i

wireframe_perspective.s: wireframe_perspective.cpp.s
.PHONY : wireframe_perspective.s

# target to generate assembly for a file
wireframe_perspective.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe_perspective.cpp.s
.PHONY : wireframe_perspective.cpp.s

wireframe_side.obj: wireframe_side.cpp.obj
.PHONY : wireframe_side.obj

# target to build an object file
wireframe_side.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe_side.cpp.obj
.PHONY : wireframe_side.cpp.obj

wireframe_side.i: wireframe_side.cpp.i
.PHONY : wireframe_side.i

# target to preprocess a source file
wireframe_side.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe_side.cpp.i
.PHONY : wireframe_side.cpp.i

wireframe_side.s: wireframe_side.cpp.s
.PHONY : wireframe_side.s

# target to generate assembly for a file
wireframe_side.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe_side.cpp.s
.PHONY : wireframe_side.cpp.s

wireframe_top.obj: wireframe_top.cpp.obj
.PHONY : wireframe_top.obj

# target to build an object file
wireframe_top.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe_top.cpp.obj
.PHONY : wireframe_top.cpp.obj

wireframe_top.i: wireframe_top.cpp.i
.PHONY : wireframe_top.i

# target to preprocess a source file
wireframe_top.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe_top.cpp.i
.PHONY : wireframe_top.cpp.i

wireframe_top.s: wireframe_top.cpp.s
.PHONY : wireframe_top.s

# target to generate assembly for a file
wireframe_top.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\programm.dir\build.make CMakeFiles/programm.dir/wireframe_top.cpp.s
.PHONY : wireframe_top.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... programm
	@echo ... camera.obj
	@echo ... camera.i
	@echo ... camera.s
	@echo ... cube.obj
	@echo ... cube.i
	@echo ... cube.s
	@echo ... dreieck.obj
	@echo ... dreieck.i
	@echo ... dreieck.s
	@echo ... farbe.obj
	@echo ... farbe.i
	@echo ... farbe.s
	@echo ... fenster.obj
	@echo ... fenster.i
	@echo ... fenster.s
	@echo ... kugel.obj
	@echo ... kugel.i
	@echo ... kugel.s
	@echo ... light.obj
	@echo ... light.i
	@echo ... light.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... material.obj
	@echo ... material.i
	@echo ... material.s
	@echo ... material_library.obj
	@echo ... material_library.i
	@echo ... material_library.s
	@echo ... mauspicking.obj
	@echo ... mauspicking.i
	@echo ... mauspicking.s
	@echo ... mausray.obj
	@echo ... mausray.i
	@echo ... mausray.s
	@echo ... mesh.obj
	@echo ... mesh.i
	@echo ... mesh.s
	@echo ... mesh_importer.obj
	@echo ... mesh_importer.i
	@echo ... mesh_importer.s
	@echo ... obj_import_dialog.obj
	@echo ... obj_import_dialog.i
	@echo ... obj_import_dialog.s
	@echo ... pfeil.obj
	@echo ... pfeil.i
	@echo ... pfeil.s
	@echo ... preprocessing.obj
	@echo ... preprocessing.i
	@echo ... preprocessing.s
	@echo ... raster_placement.obj
	@echo ... raster_placement.i
	@echo ... raster_placement.s
	@echo ... ray.obj
	@echo ... ray.i
	@echo ... ray.s
	@echo ... render.obj
	@echo ... render.i
	@echo ... render.s
	@echo ... rotations.obj
	@echo ... rotations.i
	@echo ... rotations.s
	@echo ... scene.obj
	@echo ... scene.i
	@echo ... scene.s
	@echo ... stab.obj
	@echo ... stab.i
	@echo ... stab.s
	@echo ... text3d.obj
	@echo ... text3d.i
	@echo ... text3d.s
	@echo ... threading.obj
	@echo ... threading.i
	@echo ... threading.s
	@echo ... vector3d.obj
	@echo ... vector3d.i
	@echo ... vector3d.s
	@echo ... wand.obj
	@echo ... wand.i
	@echo ... wand.s
	@echo ... wireframe.obj
	@echo ... wireframe.i
	@echo ... wireframe.s
	@echo ... wireframe_front.obj
	@echo ... wireframe_front.i
	@echo ... wireframe_front.s
	@echo ... wireframe_perspective.obj
	@echo ... wireframe_perspective.i
	@echo ... wireframe_perspective.s
	@echo ... wireframe_side.obj
	@echo ... wireframe_side.i
	@echo ... wireframe_side.s
	@echo ... wireframe_top.obj
	@echo ... wireframe_top.i
	@echo ... wireframe_top.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

